### ISSUE TITLE
OSC ops are not working in 5.0.0-fix

### ISSUE THREAD

**Issue by cristianvogel** [cables-gl/cables_electron#233]
**Describe the bug**
New patch, load the OSC extension namespace in the ops, try to add OSC or SendOSC

**Platform**
MacOs

**Dev Tools**

**Logs**

<img width="547" alt="Image" src="https://github.com/user-attachments/assets/912c66a7-8ba1-47b7-a2d7-0ffdaa688022" />

[cables.log](https://github.com/user-attachments/files/18558293/cables.log)

**Comment by cristianvogel** [comment]
ah, this is a custom op I made in previous build ```[electron-main] 27.01.2025 13:54:17 [projects_util:284] DEBUG rebuilding opdir-cache, changed by: Ops.Extension.Osc.OscArray``` 

How would I clear that out?

**Comment by cristianvogel** [comment]
I downloaded the new version 0.5.4. 

My project is reporting errors 
```[electron] failed dependency for Ops.Local.Bonjour_v2: TypeError: arg.startsWith is not a functionundefined
[electron] failed dependency for Ops.Extension.Standalone.Net.OscSend: Error: ENOTDIR: not a directory, mkdir '/Applications/cables-0.5.4.app/Contents/Resources/app.asar/dist/ops/extensions/Ops.Extension.Standalone/Ops.Extension.Standalone.Net.OscSend'undefined
[LoadingStatus] finished loading 2 assets in 0.346s
[LoadingStatus] finished loading 1 assets in 0.077s```

Do I need to somehow re-import the extensions or something?

**Comment by cristianvogel** [comment]
I looked inside the app package, and there indeed is no such directory

/Applications/cables-0.5.4.app/Contents/Resources/app.asar/dist/ops/extensions/Ops.Extension.Standalone/Ops.Extension.Standalone.Net.OscSend

There is an `app.asar.unpacked/dist/ops/extensions/Ops.Extensions.Standalone.Net.OscSend` though

**Comment by cristianvogel** [comment]
I worked around it by cloning new versions of the extension ops from an newly opened empty project. 
Then I removed the dependencies in the op description editor and re-added them. 
This seems to clear the error so far

**Comment by steam0r** [comment]
thanks, this helps a lot in finding the problem!

**Comment by cristianvogel** [comment]
It's the least I can do to help. You guys are doing amazing, empowering work!

**Comment by steam0r** [comment]
just released a hotfixed 0.5.5 which should take care of both your reported problems
